INSERT INTO rules
  ( title, description, createdAt, updatedAt )
VALUES
  ('Inspiration', 'Inspiration is a rule the game master can use to reward you for playing your character in a way that is true to his or her personality traits, ideal, bond, and flaw. By using inspiration, you can draw on your personality trait of compassion for the downtrodden to give you an edge in negotiating with the Beggar Prince. Or inspiration can let you call on your bond to the defence of your home village to push past the effect of a spell that has been laid on you.', createdAt, updatedAt),
  ('Alignment', 'A typical creature in the game world has an alignment, which broadly describes its moral and personal attitudes. Alignment is a combination of two factors: one identifies morality (good, evil, or neutral), and the other describes attitudes toward society and order (lawful, chaotic, or neutral). Thus, nine distinct alignments define the possible combinations.', createdAt, updatedAt),
  ('Ability Checks', 'An ability check tests a characters or monsters innate talent and training in an effort to overcome a challenge. The GM calls for an ability check when a character or monster attempts an action (other than an attack) that has a chance of failure. When the outcome is uncertain, the dice determine the results.', createdAt, updatedAt),
  ('Intelligence', 'Intelligence measures mental acuity, accuracy of recall, and the ability to reason.', createdAt, updatedAt),
  ('Multiclassing', 'Multiclassing	allows	you	to	gain	levels	in	multiple	classes.	Doing	so	lets	you	mix	the	abilities	of	those	classes	to	realize	a	character	concept	that	might	not	be	reflected	in	one	of	the	standard	class	options. With	this	rule,	you	have	the	option	of	gaining	a	level	in	a	new	class	whenever	you	advance	in	level,	instead	of	gaining	a	level	in	your	current	class.	Your	levels	in	all	your	classes	are	added	together	to	determine	your	character	level.	For example,	if	you	have	three	levels	in	wizard	and	two	in	fighter,	you’re	a	5th-level	character.', createdAt, updatedAt),
  ('Dexterity', 'Dexterity measures agility, reflexes, and balance.', createdAt, updatedAt),
  ('Feats', 'A feat represents a talent or an area of expertise that gives a character special capabilities. It embodies training, experience, and abilities beyond what a class provides. At certain levels, your class gives you the Ability Score Improvement feature. Using the optional feats rule, you can forgo taking that feature to take a feat of your choice instead. You can take each feat only once, unless the feats description says otherwise.', createdAt, updatedAt),
  ('Age', 'The age entry notes the age when a member of the race is considered an adult, as well as the races expected lifespan. This information can help you decide how old your character is at the start of the game. You can choose any age for your character, which could provide an explanation for some of your ability scores. For example, if you play a young or very old character, your age could explain a particularly low Strength or Constitution score, while advanced age could account for a high Intelligence or Wisdom.', createdAt, updatedAt),
  ('Size', 'Characters of most races are Medium, a size category including creatures that are roughly 4 to 8 feet tall. Members of a few races are Small (between 2 and 4 feet tall), which means that certain rules of the game affect them differently. The most important of these rules is that Small characters have trouble wielding heavy weapons, as explained in “Equipment.”', createdAt, updatedAt),
  ('Subraces', 'Some races have subraces. Members of a subrace have the traits of the parent race in addition to the traits specified for their subrace. Relationships among subraces vary significantly from race to race and world to world.', createdAt, updatedAt),
  ('Diseases', 'A disease that does more than infect a few party members is primarily a plot device. The rules help describe the effects of the disease and how it can be cured, but the specifics of how a disease works are not bound by a common set of rules. Diseases can affect any creature, and a given illness might or might not pass from one race or kind of creature to another. A plague might affect only constructs or undead, or sweep through a halfling neighborhood but leave other races untouched. What matters is the story you want to tell.', createdAt, updatedAt),
  ('Traps', 'Traps can be found almost anywhere. One wrong step in an ancient tomb might trigger a series of scything blades, which cleave through armor and bone. The seemingly innocuous vines that hang over a cave entrance might grasp and choke anyone who pushes through them. A net hidden among the trees might drop on travelers who pass underneath. In a fantasy game, unwary adventurers can fall to their deaths, be burned alive, or fall under a fusillade of poisoned darts.', createdAt, updatedAt)
  ('Madness', 'In a typical campaign, characters are not driven mad by the horrors they face and the carnage they inflict day after day, but sometimes the stress of being an adventurer can be too much to bear. If your campaign has a strong horror theme, you might want to use madness as a way to reinforce that theme, emphasizing the extraordinarily horrific nature of the threats the adventurers face.', createdAt, updatedAt),
 




Select *
From rules;